#!/usr/bin/env python3
from pathlib import Path
from statistics import mean
import json, re

ROOT=Path(__file__).resolve().parents[1]

def slug(s): return re.sub(r'[^a-z0-9]+','-',s.lower()).strip('-')

def head(title, desc, canonical, schema=''):
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title><meta name="description" content="{desc}"><link rel="canonical" href="https://voltoutpost.com{canonical}"><meta property="og:title" content="{title}"><meta property="og:description" content="{desc}"><meta property="og:type" content="website"><meta property="og:url" content="https://voltoutpost.com{canonical}"><link rel="stylesheet" href="/assets/site.css">{schema}</head><body><div class="topbar"><div class="wrap">Home energy resilience · Solar recharge · Disaster exposure · Electricity economics</div></div><header class="wrap nav"><a class="brand" href="/">VOLT<b>OUTPOST</b></a><nav class="navlinks"><a href="/rankings/">Rankings</a><a href="/calculator/">Battery Runtime</a><a href="/data-download/">Data</a><a href="/methodology/">Methodology</a><a href="/sources/">Sources</a></nav></header>'''

def footer(home=False):
    extra='<span>Related home wellness: <a href="https://inhousewellness.com/">InHouse Wellness</a></span>' if home else ''
    return f'''<footer class="footer"><div class="wrap footergrid"><span>© VoltOutpost · An independent home-energy data project.</span>{extra}<span><a href="/methodology/">Methodology</a> · <a href="/data-download/">Download data</a></span></div></footer><script src="/assets/site.js"></script></body></html>'''

def render(data):
    rows=sorted(data['cities'],key=lambda r:r['score'],reverse=True)
    for i,r in enumerate(rows,1):r['rank']=i
    generated=data.get('generated_at','starter')
    best=rows[:5]; worst=list(reversed(rows[-5:])); avg=round(mean(r['score'] for r in rows))
    home_schema='<script type="application/ld+json">'+json.dumps({'@context':'https://schema.org','@type':'Dataset','name':'VoltOutpost U.S. Home Energy Resilience Index','description':'A city-level index combining modeled solar production, seasonal solar consistency, FEMA disaster-declaration exposure and residential electricity prices.','url':'https://voltoutpost.com/data-download/','creator':{'@type':'Organization','name':'VoltOutpost'},'distribution':[{'@type':'DataDownload','encodingFormat':'text/csv','contentUrl':'https://voltoutpost.com/data/resilience-index.csv'}]})+'</script>'
    body=head('U.S. Home Energy Resilience Index | VoltOutpost','Compare U.S. cities by solar recharge potential, seasonal reliability, disaster exposure and residential electricity cost.','/',home_schema)
    body+=f'''<main><section class="wrap hero"><div><div class="eyebrow">U.S. Home Energy Resilience Index</div><h1>How resilient is your home grid?</h1><p class="lede">VoltOutpost scores major U.S. cities on four factors that shape household energy resilience: solar recharge potential, seasonal solar consistency, disaster exposure and electricity affordability.</p><div class="rule"></div><div class="panel lookup"><label>Find your city</label><div class="searchrow"><input id="cityLookup" placeholder="Start typing Austin, Phoenix, Boston…" autocomplete="off"><a class="btn" href="/rankings/">View all rankings</a></div><div id="lookupResults"></div></div></div><aside class="stamp"><div class="eyebrow">Current index</div><div class="big">{len(rows)}</div><b>U.S. cities scored</b><small>Method {data.get('method_version','1.0')} · Updated {generated}</small><hr><b>National sample average: {avg}/100</b></aside></section>
<section class="section"><div class="wrap"><div class="sectionhead"><div><div class="eyebrow">The score</div><h2>Four inputs. One comparable benchmark.</h2></div><p>The index is designed as a standardized comparison—not a claim that any location or home will remain powered during an outage.</p></div><div class="metrics"><div class="metric"><b>35%</b><span>Solar recharge potential</span></div><div class="metric"><b>20%</b><span>Seasonal solar consistency</span></div><div class="metric"><b>25%</b><span>Hazard resilience proxy</span></div><div class="metric"><b>20%</b><span>Electricity affordability</span></div></div></div></section>
<section class="section"><div class="wrap rankgrid"><div class="panel ranklist"><div class="eyebrow">Highest scores</div><h3>Top resilience cities</h3>{''.join(f'<a class="rankrow" href="/cities/{r["slug"]}/"><span class="ranknum">#{r["rank"]}</span><span><b>{r["city"]}, {r["state_abbr"]}</b><br><small>{r["annual_solar_kwh_10kw"]:,} kWh/yr standardized solar</small></span><span class="scorepill">{r["score"]}</span></a>' for r in best)}</div><div class="panel ranklist"><div class="eyebrow">Lowest scores</div><h3>Hardest resilience environments</h3>{''.join(f'<a class="rankrow" href="/cities/{r["slug"]}/"><span class="ranknum">#{r["rank"]}</span><span><b>{r["city"]}, {r["state_abbr"]}</b><br><small>{r["electricity_rate_cents_kwh"]:.1f}¢/kWh residential rate</small></span><span class="scorepill">{r["score"]}</span></a>' for r in worst)}</div></div></section>
<section class="section"><div class="wrap"><div class="sectionhead"><div><div class="eyebrow">Why this stays fresh</div><h2>Built from updateable public data.</h2></div><p>The scheduled GitHub workflow refreshes available PVWatts solar output, EIA residential electricity prices and FEMA disaster-declaration exposure, then rebuilds every city and state page.</p></div><div class="cards"><div class="card"><div class="num">01</div><h3>Solar production</h3><p>Standardized 10 kW roof-mounted solar simulations provide annual output and month-to-month consistency.</p></div><div class="card"><div class="num">02</div><h3>Disaster exposure</h3><p>County-level federal disaster declaration history is used as a simple, transparent exposure proxy—not as an outage prediction.</p></div><div class="card"><div class="num">03</div><h3>Electricity prices</h3><p>Residential retail electricity prices provide the cost component and refresh when newer data are available.</p></div></div></div></section>
<section class="section"><div class="wrap"><div class="sectionhead"><div><div class="eyebrow">Open data</div><h2>Use the index in your own work.</h2></div><p>Download the city-level CSV or JSON. Publishers may cite the VoltOutpost U.S. Home Energy Resilience Index with attribution and a link to the source page.</p></div><a class="btn dark" href="/data/resilience-index.csv">Download CSV</a> <a class="btn" href="/data-download/">Data notes</a></div></section></main>'''+footer(home=True)
    (ROOT/'index.html').write_text(body)

    rank=head('2026 U.S. Home Energy Resilience Rankings | VoltOutpost','Rank major U.S. cities by the Volt Resilience Score and its solar, seasonal, hazard and electricity-cost components.','/rankings/')
    rank+='''<main><section class="wrap cityhero"><div class="eyebrow">National ranking</div><h1>U.S. Home Energy Resilience Rankings</h1><p class="lede">A standardized city comparison intended for research, planning and discussion—not a prediction of whether a specific home will retain power.</p></section><section class="wrap section"><div class="tablewrap"><table><thead><tr><th>Rank</th><th>City</th><th>Score</th><th>Solar</th><th>Seasonal</th><th>Hazard resilience</th><th>Affordability</th><th>10 kW solar / yr</th></tr></thead><tbody>'''
    for r in rows:rank+=f'<tr><td>#{r["rank"]}</td><td><a href="/cities/{r["slug"]}/"><b>{r["city"]}, {r["state_abbr"]}</b></a></td><td><b>{r["score"]}</b></td><td>{r["solar_score"]}</td><td>{r["seasonal_score"]}</td><td>{r["hazard_resilience_score"]}</td><td>{r["affordability_score"]}</td><td>{r["annual_solar_kwh_10kw"]:,} kWh</td></tr>'
    rank+='</tbody></table></div><p class="source">Data status is recorded per city in the downloadable dataset.</p></section></main>'+footer();(ROOT/'rankings/index.html').write_text(rank)

    for r in rows:
        d=ROOT/'cities'/r['slug'];d.mkdir(parents=True,exist_ok=True)
        schema='<script type="application/ld+json">'+json.dumps({'@context':'https://schema.org','@type':'Dataset','name':f'{r["city"]}, {r["state_abbr"]} Home Energy Resilience Profile','isPartOf':{'@type':'Dataset','name':'VoltOutpost U.S. Home Energy Resilience Index','url':'https://voltoutpost.com/data-download/'},'spatialCoverage':{'@type':'Place','name':f'{r["city"]}, {r["state"]}'}})+'</script>'
        h=head(f'{r["city"]}, {r["state_abbr"]} Home Energy Resilience Score | VoltOutpost',f'Solar recharge potential, seasonal consistency, disaster exposure and residential electricity economics for {r["city"]}, {r["state_abbr"]}.',f'/cities/{r["slug"]}/',schema)
        bars=''.join(f'<span style="height:{max(7,int(v/max(r["monthly_solar_kwh_10kw"])*100))}%" data-label="{m}: {v} kWh"></span>' for m,v in zip(['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],r['monthly_solar_kwh_10kw']))
        h+=f'''<main><section class="wrap cityhero"><div class="eyebrow">City profile · Rank #{r['rank']} of {len(rows)}</div><h1>{r['city']}, {r['state_abbr']}</h1><div class="scorebox"><div class="scorecircle">{r['score']}</div><div><h2>Volt Resilience Score</h2><p class="lede">A comparative score based on standardized solar output, seasonal solar consistency, federal disaster-declaration exposure and residential electricity prices.</p><span class="tag">{r['data_status']}</span></div></div></section><section class="wrap section"><div class="cards"><div class="card"><div class="eyebrow">Solar</div><div class="num">{r['solar_score']}</div><b>{r['annual_solar_kwh_10kw']:,} kWh/year</b><p>Modeled annual AC output for a standardized 10 kW roof-mounted system.</p><div class="source">{r.get('solar_source','')}</div></div><div class="card"><div class="eyebrow">Seasonal consistency</div><div class="num">{r['seasonal_score']}</div><b>{round(r['winter_to_average_ratio']*100)}% weakest/average month</b><p>How strongly the standardized system's weakest month falls below its monthly average.</p></div><div class="card"><div class="eyebrow">Hazard resilience</div><div class="num">{r['hazard_resilience_score']}</div><b>{r['fema_disasters_20yr']} declarations in proxy window</b><p>Higher scores indicate fewer matching federal disaster declarations in the county-level proxy.</p><div class="source">{r.get('hazard_source','')}</div></div></div></section><section class="wrap section"><div class="sectionhead"><div><div class="eyebrow">Solar recharge profile</div><h2>Standardized 10 kW monthly output</h2></div><p>This profile helps show whether solar recharge is relatively consistent through the year or highly seasonal.</p></div><div class="panel" style="padding:1.2rem"><div class="mini-chart">{bars}</div></div></section><section class="wrap section"><div class="metrics"><div class="metric"><b>{r['electricity_rate_cents_kwh']:.1f}¢</b><span>Residential electricity / kWh</span></div><div class="metric"><b>{r['affordability_score']}</b><span>Affordability component</span></div><div class="metric"><b>{r['county']}</b><span>Hazard geography</span></div><div class="metric"><b>#{r['rank']}</b><span>National sample rank</span></div></div><p class="source">Electricity source: {r.get('electricity_source','')}</p><p class="note"><b>Interpret carefully.</b> This index is not an outage forecast, engineering design, insurance risk score or guarantee of backup duration. Individual homes vary materially by load, roof orientation, shading, battery size, equipment and local grid conditions.</p></section></main>'''+footer();(d/'index.html').write_text(h)

    states={}
    for r in rows:states.setdefault((r['state'],r['state_abbr'],r['state_slug']),[]).append(r)
    for (state,abbr,ss),rs in states.items():
        d=ROOT/'states'/ss;d.mkdir(parents=True,exist_ok=True);rs=sorted(rs,key=lambda x:x['score'],reverse=True);avgscore=round(mean(x['score'] for x in rs))
        h=head(f'{state} Home Energy Resilience Index | VoltOutpost',f'Compare {state} cities by solar recharge, seasonal solar consistency, disaster exposure and electricity affordability.',f'/states/{ss}/')
        h+=f'<main><section class="wrap cityhero"><div class="eyebrow">State profile</div><h1>{state}</h1><p class="lede">{len(rs)} indexed city{"ies" if len(rs)!=1 else ""} · sample average score <b>{avgscore}/100</b>.</p></section><section class="wrap section"><div class="tablewrap"><table><thead><tr><th>City</th><th>Score</th><th>Solar</th><th>Seasonal</th><th>Hazard resilience</th><th>Affordability</th></tr></thead><tbody>'
        for x in rs:h+=f'<tr><td><a href="/cities/{x["slug"]}/"><b>{x["city"]}</b></a></td><td>{x["score"]}</td><td>{x["solar_score"]}</td><td>{x["seasonal_score"]}</td><td>{x["hazard_resilience_score"]}</td><td>{x["affordability_score"]}</td></tr>'
        h+='</tbody></table></div></section></main>'+footer();(d/'index.html').write_text(h)
    urls=['/','/rankings/','/calculator/','/methodology/','/data-download/','/sources/']+[f'/cities/{r["slug"]}/' for r in rows]+[f'/states/{ss}/' for _,_,ss in states]
    sitemap='<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+''.join(f'<url><loc>https://voltoutpost.com{u}</loc></url>\n' for u in urls)+'</urlset>'
    (ROOT/'sitemap.xml').write_text(sitemap)

if __name__=='__main__':
    with open(ROOT/'data/resilience-index.json') as f:data=json.load(f)
    render(data)
